<?php

/**
 * @var \Hiberus\HiberusRebollar\Block\Index $block
 */
$alumnos = $block->getNotas();
$arrayNotas = $block->getMejoresNotas();
$maximoElementos = $block->getElementos();
$marcaAprobado = $block->getNota();
if(!isset($maximoElementos)){
    $maximoElementos=count($alumnos);
}

?>


<div><button id="ocultarNotas" >Ocultar/Mostrar notas</button></div>
<div><button id="maxNota" >Mostrar mayor nota</button></div>
<h2 class="title">Alumnos</h2>

<div id="notas">
<?php
    $media=0;
    $coincide=false;
    $count=0;

foreach($alumnos as $alumno) {
if($maximoElementos>$count){
    $media+=$alumno->getMark();

    for($i=0;$i<3;$i++) {
        if ($arrayNotas[$i] == $alumno->getMark()) {
            $coincide = true;
        }
    }?>

       <?php if($alumno->getMark()<$marcaAprobado){?>
            <ul class="suspenso " >
       <?php }else{?>
            <ul class="aprobado " >
<?php
         }
        if($coincide){ ?>
                <li><h2>Nombre:<?= $alumno->getNombre(); ?></h2></li>
                <li><h2>Apellido: <?= $alumno->getApellido(); ?></h2></li>
                <li><h2>Nota:<?= $alumno->getMark(); ?></h2></li>
            <?php }else{ ?>
                <li>Nombre:<?= $alumno->getNombre(); ?></li>
                <li>Apellido: <?= $alumno->getApellido(); ?></li>
                <li>Nota:<?= $alumno->getMark(); ?></li>

            <hr>


<?php
}
        echo '</ul>';

}
$coincide=false;
$count++;
} ?>

</div>
<p> Total number of students: <?= count($alumnos) ?> </p>
<p> Media: <?= $media/count($alumnos) ?> </p>
<script>
    require(['jquery','ocultarNotas'],function($,ocultarNotas){
        $(document).on("click","#ocultarNotas", function() {
            ocultarNotas();
        });
    });


        require([
        'jquery',
        'Magento_Ui/js/modal/alert'], function($, alert) {
            $('#maxNota').on('click', function(e){
                alert({
                title: 'Mejor Nota',
                content: $('<div>La mejor nota es : <?= max($arrayNotas) ?></div>'),
                modalClass: 'alert',
                    buttons: [{
                        text: $.mage.__('Aceptar'),
                        class: 'action primary accept',

                        /**
                         * Click handler.
                         */
                        click: function () {
                            this.closeModal(true);
                        }
                    }]

                })
            })
         }
        );

</script>
