<?php

/**
 * @var \Hiberus\HiberusRebollar\Block\Index $block
 */
$alumnos = $block->getNotas();
$mejoresnotas = $block->getMejoresNotas();
$maximoElementos = $block->getElementos();
$marcaAprobado = $block->getNota();

?>

<h2 class="title">Alumnos</h2>

<?php
    $media=0;
    $coincide=false;
    $count=0;

foreach($alumnos as $alumno) {
if($maximoElementos<$count+1){
    $media+=$alumno->getMark();

    for($i=0;$i<3;$i++) {
        if ($mejoresnotas[$i] == $alumno->getMark()) {
            $coincide = true;
        }
    }?>

       <?php if($alumno->getMark()<$marcaAprobado){?>
            <ul class="suspenso">
    <?php }else{?>
            <ul class="aprobado">
<?php
    }
        if($coincide){ ?>
                <li><h2>Nombre:<?= $alumno->getNombre(); ?></h2></li>
                <li><h2>Apellido: <?= $alumno->getApellido(); ?></h2></li>
                <li><h2>Nota:<?= $alumno->getMark(); ?></h2></li>
            <?php }else{ ?>
                <li>Nombre:<?= $alumno->getNombre(); ?></li>
                <li>Apellido: <?= $alumno->getApellido(); ?></li>
                <li>Nota:<?= $alumno->getMark(); ?></li>

            <hr>


<?php
}
        echo '</ul>';

}
$coincide=false;
$count++;
} ?>


<p> Total number of students: <?= count($alumnos) ?> </p>
<p> Media: <?= $media/count($alumnos) ?> </p>
